### ISSUE TITLE
"DUIK_Two_Layer_IK" in DuIK14 is missing in DuIK15 RC1

### ISSUE THREAD

**Issue by eZioPan** [Duduf-dev/Duik#162]
![2015-08-23_15-39-36](https://cloud.githubusercontent.com/assets/10928361/9427374/347670e8-49ad-11e5-976a-1b691df0b706.jpg)

Hi! There is a missing effects called "DUIK_Two_Layer_IK" in DuIK15 RC1.
I create my AE project with DuIK14, and when I open it with DuIK15 Beta 4b, there is no problem. But it ask me to intall effect with DuIK15 RC1.
I think you just change something, so I wonder will you make DuIK15 backward compatible, or should I do something to convert it into new version?
btw, I love the new UI!
Thank you!

**Comment by Nico-Duduf** [comment]
Hi,
this "DUIK_Two_Layer_IK" is what's called a "pseudo effect" in AE, and the rig using it should work even if it's missing, it's not "really" needed. So Duik is backward compatible, it's just After Effects warning for something it shouldn't (it really should not warn for missing pseudo effects, I don't know why it does).

The details: Duik 15 was using this "DUIK_Two_Layer_IK" effect, up to version beta4b, but I had to remove it in RC1 in order to replace it with a new version (there's a new "auto-shrink" value in the IK).
I could have let the old effect installed along with the new, but as I update Duik and change things in the pseudo effects, that would mean keeping a lot of deprecated effects just to avoid an error message; so what I chose to do is to remove effects used only by beta versions, but I think I'm going to always keep effects I'll use for major versions.
This way, only beta testers may have this error message with some of their rigs created with beta versions, but casual users won't see anything.
